name: dbt CI

on:
  pull_request:
    branches: [main]

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
          pip install dbt-bigquery==1.7.5

      - name: Write GCP service account key
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json

      - name: Write dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          default:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: service-account
                project: databird-498212
                dataset: ci_localbike
                keyfile: $HOME/gcp-key.json
                threads: 4
                location: US
          EOF

      - name: dbt build
        working-directory: dbt
        run: dbt build --profiles-dir ~/.dbt