name: dbt CI

on:
  pull_request:
    branches: [main]

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install dbt-bigquery

      - name: Authenticate to BigQuery
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          votre_projet_dbt:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: service-account
                project: databird-498212
                dataset: dbt_ci
                keyfile: $HOME/gcp-key.json
                threads: 4
                location: US
          EOF

      - name: dbt deps
        run: dbt deps

      - name: dbt build
        run: dbt build